<?php

namespace LVBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubTitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubTitleRepository extends EntityRepository
{
}
