user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

lv:
    resource: "@LVBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"